name: irc_message
version: 1.0.2
author: Fionn Kelleher <me@fionn.co>
description: Modern IRC parser
homepage: https://github.com/expr/dart-irc_message
dev_dependencies:
  unittest: '>=0.10.1+2 <0.11.0'
